### ISSUE TITLE
Wp visualization enhancements

### ISSUE THREAD

**Issue by tstastny** [ethz-asl/qgc_asl#29]
**TODO**

- [x] show final approach of FW landing pattern on flight map (carry over from #27)
- [x] calculate landing pattern from landing angle
- [ ] show probable landing area around land point
- [ ] wind considerations? (possibly more on pixhawk side)
- [ ] show small arrow indicating direction of loiter circles
- [ ] default acceptance radius in loiter-to-alt simple edit mode to zero, and don't show it on the editor. Only the FW landing pattern complex mission item will use the LOITER_DOWN option, which uses this acceptance radius.

**Comment by philipoe** [comment]
@tstastny Can we close this?

**Comment by tstastny** [comment]
deprecated
