### ISSUE TITLE
Piksi SBP communication with QGC

### ISSUE THREAD

**Issue by hitimo** [ethz-asl/qgc_asl#30]
This is already implemented for Mission Planner / ArduPilot: The Swift console communicates via the SBP Protocol with MissionPlanner. The RTK corrections are then sent to the drone via 3dr link.

**References**
- [piksi-multi-ardupilot-integration-guide](https://support.swiftnav.com/customer/portal/articles/2803651-piksi-multi-ardupilot-integration-guide)
- [piksi-ardupilot-integration-guide](http://docs.swiftnav.com/wiki/Integrating_Piksi_with_the_Pixhawk_platform)
- [swift-nav/libsbp](https://github.com/swift-nav/libsbp)
- [Send SBP via UDP from Piksi Console](http://docs.swiftnav.com/wiki/Alternate_Radio_Setup_(Send_SBP_over_UDP))
- [Piksi rotorS and more](https://bitbucket.org/Daniel-Eckert/mav_localization)

**TODOs**
- [ ] [Test communication via WiFi first](https://github.com/ethz-asl/mav_rtk_gps/tree/master/piksi_rtk_gps)
- [ ] Communication between SBP and QGC via UDP
- [ ] Inject GPS correction data into mavlink stream (similar to [MissionPlanner](https://github.com/ArduPilot/MissionPlanner/blob/454fb85704b6ffbada8d996a2da4874a105d2cc4/Mavlink/MAVLinkInterface.cs#L2595-L2647))

---

![800px-dedicated_radio_layout](https://cloud.githubusercontent.com/assets/5558652/26530938/ad2effc2-43df-11e7-8ca8-bc6140a3a62b.jpg)
![ground_station_resize-1](https://cloud.githubusercontent.com/assets/5558652/26530945/e3befc36-43df-11e7-97ba-bab7e8770c90.png)

**Comment by philipoe** [comment]
@hitimo Any update on how this works with the current QGC (v3.3+)? Do we still need this issue given that we are basically working with the standard QGC now? If not, please close this issue.

**Comment by philipoe** [comment]
@hitimo *ping*

**Comment by hitimo** [comment]
closing as PPK is all I'm interested in currently.
